// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ab23af16-df87-4378-9fc2-343ee7aed26f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onGraphChange();
void onDistanceChange();
void onLedChange();
void onLed2Change();

float graph;
int distance;
CloudLocation location;
bool led;
bool led2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(graph, READWRITE, ON_CHANGE, onGraphChange, 1);
  ArduinoCloud.addProperty(distance, READWRITE, ON_CHANGE, onDistanceChange, 1);
  ArduinoCloud.addProperty(location, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange, 5);
  ArduinoCloud.addProperty(led2, READWRITE, ON_CHANGE, onLed2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
